#!/bin/bash

#Authour: Omar AbdelWahab
#Date Created:  30/08/2023
#Date Modified: 04/09/2023

#Description:
# This script should backup all the files
# in your home directory and save them all
# in a .tar archive.

# /home/cmo/Omar/Udemy - Bash Mastery The Complete Guide to Bash Shell Scripting 2021-4/home backups
# folder of all files in the home directory

#Usage:
#	backupMH

currentdir=$(pwd)

echo "Hello, ${USER^}
I will now back up your home directory, $HOME"

echo "You are running this script from $currentdir
Therefore, I will save the backup in $currentdir"

tar -cf "$currentdir/my_backup_$(date +%d-%m-%Y_%H-%M-%S)".tar $HOME/Omar/* 2>/dev/null

echo "Backup Completed Successfully."

exit 0