#!/bin/bash

#Date Created  09/10/2023
#Date Modified 09/10/2023
#Author: Omar AbdelWahab

#Description:
#city checker

PS3="Please, choose a city: "
select city in "Tokyo" "London" "Los Angeles" "Moscow" "Dubai" "Manchester" "New York" "Paris" "Bangalore" "Johannesburg" "Istanbul" "Milan" "Abu Dhabi" "Pune" "Nairobi" "Berlin" "Karachi";
do
	case "$city" in
	"Tokyo")
	echo "Japan";;
	"London"|"Manchester")
	echo "United Kingdom";;
	"Los Angeles"|"New York")
	echo "United States of America";;
	"Moscow")
	echo "Russia";;
	"Dubai"|"Abu Dhabi")
	echo "United Arab Emirates";;
	"Paris")
	echo "France";;
	"Bangalore"|"Pune")
	echo "India";;
	"Johannesburg")
	echo "South Africa";;
	"Istanbul")
	echo "Turkey";;
	"Milan")
	echo "Italy";;
	"Nairobi")
	echo "Kenya";;
	"Berlin")
	echo "Germany";;
	"Karachi")
	echo "Pakistan";;
	*)
	echo "You've choosen unlisted city." # run these if no other pattern matches
	;;
	esac

break;
done

exit 0