#!/bin/bash

#Date Created  18/09/2023
#Date Modified 18/09/2023
#Author: Omar AbdelWahab

#Description:
#getextentions

read -p "What is your first name?: " fname
read -p "What is your surname/family name?: " sname

echo -e "\nExtension Number must be exactly 4 digits."
echo -e "The first 4 digits will be considered as your input."
read -N 4 -p "What is your extension number?: " ext

echo -e "\n\nAccess Code must be exactly 4 digits."
echo -e "The first 4 digits will be considered as your input."
read -s -N 4 -p"What access code would you like to use when dialing in?: " acode
echo -e "\n"



PS3="Kindly, choose either a Handheld or a Headset Phone: "
select type in Handheld Headset;
do
echo "You've chosen a $type Phone."
break
done

PS3="Kindly, choose your department: "
select department in finance sales "customer Service" engineering;
do
echo "You've chosen $department department."
break
done

echo "$fname,$sname,$ext,$acode,$type,$department" >> extensions.csv

exit 0