#!/bin/bash

#Date Created  11/10/2023
#Date Modified 11/10/2023
#Author: Omar AbdelWahab

#Description:
#Timer

total_seconds=0

while getopts "m:s:" opt;
do
case "$opt" in
	m) total_seconds=$(($total_seconds + $OPTARG * 60));;
	s) total_seconds=$(($total_seconds + $OPTARG));;
   \?) echo "You've used an invalid option.";;
esac
done

while [ $total_seconds -gt 0 ]; 
do
	echo "Total Seconds Remaining: $total_seconds"
	total_seconds=$(($total_seconds - 1))
	sleep 1s
done;

echo "Time's Up!"

exit 0